name: Build

on: [push, pull_request, release]

jobs:
    build_mac:
      name: Train, evaluate and build Mac wheels
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [macos-latest]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Train-eval model
          run: |
              cd ro_legal_fl && \
              pip3 install -r requirements.txt && \
              python3 scripts/set_spacy_version.py && \
              python3 -m spacy project assets && \
              python3 -m spacy project run either-download-embeddings && \
              python3 -m spacy project run all

        - name: Upload best model
          uses: actions/upload-artifact@v3
          with:
            name: macos-latest-model-best.tar.gz
            path: ro_legal_fl/packages/model-best.tar.gz

        - name: Build MacOS wheel
          run: |
              cd ro_legal_fl && \
              python3 -m spacy project run wheel && \
              tar -cvf ro_legal_fl/packages/package.tar.gz ro_legal_fl/packages/ro_legal_fl-*

        - name: Upload wheel
          uses: actions/upload-artifact@v3
          with:
            name: ro_legal_fl_macos-latest.whl
            path: ro_legal_fl/packages/*/dist/*.whl

        - name: Upload tar
          uses: actions/upload-artifact@v3
          with:
            name: macos-latest-package.tar.gz
            path: ro_legal_fl/packages/package.tar.gz


    build_linux:
      name: Train, evaluate and build linux wheels
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-22.04]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Train-eval model
          run: |
              cd ro_legal_fl && \
              pip3 install -r requirements.txt && \
              python3 scripts/set_spacy_version.py && \
              python3 -m spacy project assets && \
              python3 -m spacy project run either-download-embeddings && \
              python3 -m spacy project run all

        - name: Upload best model
          uses: actions/upload-artifact@v3
          with:
            name: ubuntu-22.04-model-best.tar.gz
            path: ro_legal_fl/packages/model-best.tar.gz

        - name: Build Linux wheel
          run: |
              cd ro_legal_fl && \
              python3 -m spacy project run wheel && \
              tar -cvf ro_legal_fl/packages/package.tar.gz ro_legal_fl/packages/ro_legal_fl-*

        - name: Upload wheel
          uses: actions/upload-artifact@v3
          with:
            name: ro_legal_fl_ubuntu-22.04.whl
            path: ro_legal_fl/packages/*/dist/*.whl

        - name: Upload tar
          uses: actions/upload-artifact@v3
          with:
            name: ubuntu-22.04-package.tar.gz
            path: ro_legal_fl/packages/package.tar.gz


    build_windows:
      name: Train, evaluate and build Windows wheels
      if: false
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Train-eval model
          run: |
              cd ro_legal_fl && 
              pip3 install -r requirements.txt && 
              python3 scripts/set_spacy_version.py && 
              python3 -m spacy project assets && 
              python3 -m spacy project run either-download-embeddings && 
              python3 -m spacy project run all

        - name: Upload best model
          uses: actions/upload-artifact@v3
          with:
            name: mac-model-best.tar.gz
            path: packages/model-best.tar.gz

        - name: Build Windows wheel
          run: |
              cd ro_legal_fl && 
              python3 -m spacy project run wheel

        - name: Upload wheel
          uses: actions/upload-artifact@v3
          with:
            name: linux.whl
            path: ro_legal_fl/packages/*/dist/*.whl

