name: Build

on: [push, pull_request, release]

jobs:
    build_linux_wheels:
      name: Build linux wheels
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-20.04]
      steps:
        - name: Build wheels
          run: |
              cd ro_legal_fl && \
              pip install -r requirements.txt && \
              python -m spacy project run all either-download-embeddings && \
              python -m spacy project assets && \
              python -m spacy project run all
        - uses: actions/upload-artifact@v2
          with:
            name: wheels
            path: ro_legal_fl/packages/ro_legal_fl-0.1.0/dist/*.whl
