name: Build

on: [push, pull_request, release]

jobs:
    build_mac_wheels:
      name: Build Mac wheels
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [macos-latest]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build wheels
          run: |
              cd ro_legal_fl && \
              pip3 install -r requirements.txt && \
              python3 scripts/set_spacy_version.py && \
              python3 -m spacy project assets && \
              python3 -m spacy project run either-download-embeddings && \
              python3 -m spacy project run all

        - name: Upload
          uses: actions/upload-artifact@v3
          with:
            name: mac.whl
            path: ro_legal_fl/packages/*/dist/*.whl

    build_linux_wheels:
      name: Build linux wheels
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-22.04]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build wheels
          run: |
              cd ro_legal_fl && \
              pip3 install -r requirements.txt && \
              python3 scripts/set_spacy_version.py && \
              python3 -m spacy project assets && \
              python3 -m spacy project run either-download-embeddings && \
              python3 -m spacy project run all

        - name: Upload
          uses: actions/upload-artifact@v3
          with:
            name: linux.whl
            path: ro_legal_fl/packages/*/dist/*.whl

    build_win_wheels:
      name: Build Windows wheels
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build wheels
          run: |
              cd ro_legal_fl && 
              pip3 install -r requirements.txt && 
              python3 scripts/set_spacy_version.py && 
              python3 -m spacy project assets && 
              python3 -m spacy project run either-download-embeddings && 
              python3 -m spacy project run all

        - name: Upload
          uses: actions/upload-artifact@v3
          with:
            name: win.whl
            path: ro_legal_fl/packages/*/dist/*.whl
